"""
Side-panel reference content for each MACCRE workbook sheet.
Imported by generate_global_template.py — do not run directly.
Each constant is a list[tuple[str,str]] of (style, text) rows where style is:
  'title'   dark header row
  'section' subsection header
  'rule'    monospaced key-value or code line
  'body'    wrapped prose
  'blank'   empty spacer
"""

PANEL_PROJECT: list[tuple[str, str]] = [
    ("title",   "\U0001f4d6  PROJECT DEFINITION — REFERENCE"),
    ("blank",   ""),
    ("section", "DATACENTER  6-Tier Layout"),
    ("rule",    "  01_Raw_Source      Input docs (PDFs, MDs, TXTs)"),
    ("rule",    "  02_Dynamic_Context topology.csv + agent_roster.csv"),
    ("rule",    "  03_Agent_Ledgers   JSON thought audits, session logs"),
    ("rule",    "  04_Code_Artifacts  Agent-generated output"),
    ("rule",    "  05_Rendered_Media  TTS + A/V pipeline output"),
    ("rule",    "  02_Dynamic_Context/memory_pins  Semantic anchors, cross-project"),
    ("blank",   ""),
    ("section", "PROJECT_NAME"),
    ("body",    "New name \u2192 silo auto-provisioned at fire time."),
    ("body",    "Existing name \u2192 selects that project\u2019s context."),
    ("blank",   ""),
    ("section", "LINKED_PROJECTS"),
    ("body",    "Comma-separated silos for Synaptic Bridge memory"),
    ("body",    "federation. Agents can query_foreign_memory across."),
    ("blank",   ""),
    ("section", "FIRE COMMANDS"),
    ("rule",    "  python maccre.py global"),
    ("rule",    "  python maccre.py workbook fire"),
    ("blank",   ""),
    ("section", "KEY RULE"),
    ("body",    "\u2605 fields are required. EXECUTION_PLAN shows readiness"),
    ("body",    "status (READY / PARTIAL / INCOMPLETE) before you fire."),
]

PANEL_AGENTS: list[tuple[str, str]] = [
    ("title",   "\U0001f4d6  AGENTS — REFERENCE"),
    ("blank",   ""),
    ("section", "ROLES  (col C)  \u2014 Diamond Loop position"),
    ("rule",    "  Researcher   temp 1.0  Early pipeline. Data gathering."),
    ("rule",    "  Writer       temp 1.0  Content generation."),
    ("rule",    "  Synthesiser  temp 1.0  Fan-in merge. Use with WAIT_FOR."),
    ("rule",    "  Director     temp 1.0  Orchestration and routing logic."),
    ("rule",    "  Critic       temp 0.1  Quality gate. Loops w/ MAX_REC."),
    ("rule",    "  Extractor    temp 0.1  Structured output. json required."),
    ("rule",    "  Verifier     temp 0.1  OSINT epistemic gate. Pre-render."),
    ("rule",    "  Renderer     temp 0.1  Fires A/V pipeline. Terminal."),
    ("rule",    "  Archivist    temp 0.1  Writes to knowledge store."),
    ("rule",    "  Router       temp 1.0  Pure routing. Minimal generation."),
    ("blank",   ""),
    ("section", "SEARCH_GROUNDING  (col K)"),
    ("rule",    "  Local Only        Thought pins \u2192 vector query. Default."),
    ("rule",    "  Google            Gemini native search grounding."),
    ("rule",    "  Brave             Brave Search API. Add search_web tool."),
    ("rule",    "  Hybrid            Google feeds Brave sequentially."),
    ("rule",    "  Hybrid-Synthesis  Parallel G+B \u2192 dedup \u2192 labelled list."),
    ("body",    "  Hybrid-Synthesis: use execute_hybrid_synthesis tool."),
    ("blank",   ""),
    ("section", "RESPONSE_FORMAT  (col L)"),
    ("rule",    "  markdown  Prose output. Default for generators."),
    ("rule",    "  json      API-enforced. Required: Extractor / Critic."),
    ("rule",    "  text      Plain text, no formatting."),
    ("blank",   ""),
    ("section", "TEMPERATURE \u2014 Diamond Loop Doctrine"),
    ("rule",    "  1.0  Generators: Researcher, Writer, Director"),
    ("rule",    "  0.1  Critics:    Extractor, Critic, Verifier"),
    ("blank",   ""),
    ("section", "TOOLS  (col F) \u2014 pipe-separated, e.g. search_web|write_file"),
    ("blank",   ""),
    ("section", "  Web & OSINT"),
    ("rule",    "  search_web               Brave Search API"),
    ("rule",    "  read_url_content          Fetch + parse a URL"),
    ("rule",    "  execute_hybrid_synthesis  G+B parallel dedup search"),
    ("section", "  Memory & RAG"),
    ("rule",    "  query_local_memory        Vector search in project silo"),
    ("rule",    "  fts_search_memory         BM25 full-text search"),
    ("rule",    "  ingest_document           Hash-aware doc ingest"),
    ("rule",    "  query_foreign_memory      Search linked project silo"),
    ("rule",    "  import_foreign_vectors    Pull vectors from linked silo"),
    ("rule",    "  prune_semantic_memory     Remove stale embeddings"),
    ("section", "  File I/O"),
    ("rule",    "  read_file                 Read from DATACENTER"),
    ("rule",    "  write_file                Write to 04_ or 05_ tier"),
    ("rule",    "  file_exists               Check DATACENTER path"),
    ("rule",    "  trash_file                Move file to trash (needs elevation)"),
    ("section", "  Telemetry"),
    ("rule",    "  query_thoughts            Read L1 session thoughts"),
    ("rule",    "  query_telemetry_matrix    Query cost + event data"),
    ("rule",    "  read_local_codebase       Self-audit Python source"),
    ("rule",    "  generate_telemetry_report FinOps + telemetry summary"),
    ("rule",    "  rotate_logs               Archive and purge logs"),
    ("section", "  Render & FinOps"),
    ("rule",    "  execute_render_pipeline   Fire TTS+image+FFmpeg"),
    ("rule",    "  estimate_manifest_cost    USD cost estimate (pre-fire)"),
    ("section", "  Orchestration"),
    ("rule",    "  mint_agent                Create agent definition"),
    ("rule",    "  build_topology            Build topology CSV"),
    ("rule",    "  link_projects             Synaptic Bridge two silos"),
    ("rule",    "  ignite_swarm              Inject payload + start swarm"),
    ("rule",    "  initialize_workspace      Provision 6-tier silo"),
    ("rule",    "  switch_workspace          Change active project"),
    ("rule",    "  request_elevation         PIN-gate for privileged ops"),
    ("rule",    "  promote_topology_to_library  Save topology to library"),
    ("rule",    "  recall_topology           Load named topology"),
    ("rule",    "  design_swarm              Agentic swarm design"),
    ("rule",    "  run_swarm                 Execute swarm worker loop"),
    ("rule",    "  create_persona_card       Generate agent persona"),
    ("section", "  Sync & Utilities"),
    ("rule",    "  export_project_nugget     Export nugget to Drive"),
    ("rule",    "  import_project_nuggets    Import nuggets from Drive"),
    ("rule",    "  list_project_nuggets      List Drive nuggets"),
    ("rule",    "  ensure_project_workbook   Guarantee Session.xlsx exists"),
]

PANEL_TOPOLOGY: list[tuple[str, str]] = [
    ("title",   "\U0001f4d6  TOPOLOGY — REFERENCE"),
    ("blank",   ""),
    ("section", "NODE_ID  (col A)"),
    ("body",    "Unique name. Convention: ROLE_PURPOSE"),
    ("body",    "Example: RESEARCHER_OSINT, CRITIC_QUALITY"),
    ("blank",   ""),
    ("section", "NEXT_NODE  (col C) \u2014 terminal keywords"),
    ("rule",    "  STOP    Clean termination  (primary keyword)"),
    ("rule",    "  DONE    Alias for STOP"),
    ("rule",    "  FAILED  Error termination path"),
    ("blank",   ""),
    ("section", "WAIT_FOR  (col G) \u2014 fan-in gate"),
    ("body",    "Comma-separated NODE_IDs this node waits for."),
    ("body",    "Fires only after ALL listed nodes complete."),
    ("body",    "Use for Synthesiser nodes merging parallel paths."),
    ("body",    "Example: WAIT_FOR = OSINT_GOOGLE,OSINT_BRAVE"),
    ("blank",   ""),
    ("section", "FAILURE_TARGET  (col H) \u2014 circuit breaker"),
    ("body",    "Route here if node hits error or MAX_RECURSION"),
    ("body",    "expires. Typically STOP or DONE."),
    ("blank",   ""),
    ("section", "MAX_RECURSION  (col I)"),
    ("body",    "SQLite queue-level counter. Not agent reasoning."),
    ("rule",    "  0  Executes once. Re-entry \u2192 FAILURE_TARGET."),
    ("rule",    "  3  Initial + 3 re-entries = 4 total executions."),
    ("body",    "Critic loop: Critic MAX=3, Writer MAX=0."),
    ("blank",   ""),
    ("section", "\u2500\u2500\u2500 PATTERNS \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500"),
    ("blank",   ""),
    ("section", "CRITIC LOOP"),
    ("rule",    "  WRITER  Writer   NEXT:CRITIC   MAX_REC:0"),
    ("rule",    "  CRITIC  Critic   NEXT:STOP     MAX_REC:3"),
    ("body",    "  Critic instruction: Score 1-10. If \u22658: ROUTE:STOP."),
    ("body",    "  If <8: ROUTE:WRITER with revision notes."),
    ("blank",   ""),
    ("section", "FAN-OUT / FAN-IN"),
    ("rule",    "  FORK    Director    NEXT:PATH_A"),
    ("rule",    "  PATH_A  Researcher  NEXT:MERGER"),
    ("rule",    "  PATH_B  Researcher  NEXT:MERGER"),
    ("rule",    "  MERGER  Synthesiser NEXT:STOP  WAIT_FOR:PATH_A,PATH_B"),
    ("blank",   ""),
    ("section", "HYBRID-SYNTHESIS OSINT"),
    ("rule",    "  OSINT_G  Researcher NEXT:DEDUP GROUNDING:Google"),
    ("rule",    "  OSINT_B  Researcher NEXT:DEDUP GROUNDING:Brave"),
    ("rule",    "  DEDUP    Extractor  NEXT:SYNTH WAIT_FOR:OSINT_G,OSINT_B"),
    ("rule",    "  SYNTH    Synthesiser NEXT:STOP"),
]

PANEL_SWARM: list[tuple[str, str]] = [
    ("title",   "\U0001f4d6  SWARM REQUEST — REFERENCE"),
    ("blank",   ""),
    ("section", "PAYLOAD_TEXT vs PAYLOAD_PATH"),
    ("body",    "PAYLOAD_TEXT takes priority if both are filled."),
    ("body",    "Use TEXT for short inline prompts."),
    ("body",    "Use PATH for large docs in 01_Raw_Source."),
    ("blank",   ""),
    ("section", "START_NODE"),
    ("body",    "NODE_ID where the swarm enters the topology."),
    ("body",    "Leave blank \u2192 first row of TOPOLOGY sheet."),
    ("blank",   ""),
    ("section", "COMPUTE_TIER"),
    ("rule",    "  cloud  Gemini API  (default)"),
    ("rule",    "  edge   On-device / low-bandwidth models"),
    ("rule",    "  local  Ollama / Gemma local endpoint"),
    ("blank",   ""),
    ("section", "FIRE COMMANDS"),
    ("rule",    "  python maccre.py global"),
    ("rule",    "  python maccre.py workbook fire"),
]

PANEL_SESSION: list[tuple[str, str]] = [
    ("title",   "\U0001f4d6  SESSION CONFIG — REFERENCE"),
    ("blank",   ""),
    ("section", "INGEST_BEFORE_RUN"),
    ("body",    "TRUE \u2192 hash-aware ingest of 01_Raw_Source before"),
    ("body",    "swarm starts. Embeds new / changed documents."),
    ("blank",   ""),
    ("section", "CANONIZE_AFTER_RUN"),
    ("body",    "TRUE \u2192 merge L1 session memory into L2 project"),
    ("body",    "memory after swarm completes."),
    ("body",    "CLI: maccre.py canonize --project P --session S"),
    ("blank",   ""),
    ("section", "OUTPUT_FORMATS"),
    ("body",    "Comma-separated: md, txt, json, mp3, mp4"),
    ("rule",    "  md/txt/json  \u2192 04_Code_Artifacts"),
    ("rule",    "  mp3/mp4      \u2192 05_Rendered_Media"),
    ("blank",   ""),
    ("section", "HOT-MIC  (live override during run)"),
    ("rule",    "  maccre.py intercept <session_id> \"<message>\""),
    ("body",    "Injects priority instruction into running swarm."),
]
