# ┌─────────────────────────────────────────────────────────────────────────────┐
# │  MACCREv2 ENGINEERING DOCTRINE                             Law Rev: 19.0   │
# ├─────────────────────────────────────────────────────────────────────────────┤
# │  VI.  ABSTRACTION All I/O behind abc.ABC before any concrete driver.       │
# └─────────────────────────────────────────────────────────────────────────────┘
"""
maccre_core/_net/client_interface.py
====================================
Phase 0B — Strangler Fig ABC for the Inference Client.

Defines the ``InferenceClient`` interface contract that ``GeminiClient``
(sovereign HTTP) implements today.  Positions ``OllamaClient`` (local Gemma)
as a future drop-in replacement for the Dual-Pipeline Edge stack.
"""
from __future__ import annotations

import abc
from typing import Any, Generator


class InferenceResponse(abc.ABC):
    """Abstract response envelope from an inference call."""

    @property
    @abc.abstractmethod
    def text(self) -> str:
        """The generated text content."""

    @property
    @abc.abstractmethod
    def function_call(self) -> tuple[str, dict[str, Any]] | None:
        """Parsed function call (name, args) if the model requested a tool, else None."""

    @property
    @abc.abstractmethod
    def prompt_tokens(self) -> int:
        """Number of tokens consumed by the prompt."""

    @property
    @abc.abstractmethod
    def candidate_tokens(self) -> int:
        """Number of tokens generated by the model."""

    @property
    @abc.abstractmethod
    def raw(self) -> dict[str, Any]:
        """The raw API response dict for debugging/logging."""


class EmbeddingResult(abc.ABC):
    """Abstract embedding vector result."""

    @property
    @abc.abstractmethod
    def values(self) -> list[float]:
        """The embedding vector as a list of floats."""


class InferenceClient(abc.ABC):
    """Abstract interface for LLM inference providers.

    All orchestration components (SwarmWorker, NexusAgent, FlowRunner)
    MUST type-hint against this ABC, never against a concrete client.

    Current concrete driver: ``GeminiClient`` (sovereign HTTP, zero dependencies).
    Future drivers: ``OllamaClient`` (local Gemma), ``VertexClient`` (enterprise).
    """

    # ── Text Generation ───────────────────────────────────────────────────────

    @abc.abstractmethod
    def generate_content(
        self,
        model: str,
        contents: list[dict[str, Any]],
        system_instruction: str | None = None,
        temperature: float = 0.7,
        tool_declarations: list[dict[str, Any]] | None = None,
        search_grounding: bool = False,
        disable_auto_function_calling: bool = True,
        response_schema: dict[str, Any] | None = None,
        safety_settings: list[dict[str, str]] | None = None,
        max_output_tokens: int | None = None,
        cached_content_uri: str | None = None,
        thinking_config: dict[str, Any] | None = None,
    ) -> InferenceResponse:
        """Standard (non-streaming) generation call.

        Args:
            model: Model identifier (e.g. ``'gemini-2.5-flash'``).
            contents: Conversation turns as content dicts.
            system_instruction: System prompt string.
            temperature: Sampling temperature (0.0–2.0).
            tool_declarations: Function declarations for tool use.
            search_grounding: Enable live web search grounding.

        Returns:
            An InferenceResponse with text, function_call, and token counts.
        """

    @abc.abstractmethod
    def stream_generate_content(
        self,
        model: str,
        contents: list[dict[str, Any]],
        system_instruction: str | None = None,
        temperature: float = 0.7,
        tool_declarations: list[dict[str, Any]] | None = None,
        search_grounding: bool = False,
        response_schema: dict[str, Any] | None = None,
        safety_settings: list[dict[str, str]] | None = None,
        max_output_tokens: int | None = None,
        cached_content_uri: str | None = None,
    ) -> Generator[str, None, None]:
        """Streaming generation — yields text tokens as they arrive."""

    # ── Embeddings ────────────────────────────────────────────────────────────

    @abc.abstractmethod
    def embed_content(
        self,
        model: str,
        text: str,
        task_type: str = "RETRIEVAL_DOCUMENT",
    ) -> EmbeddingResult:
        """Embed a single text string into a vector."""

    @abc.abstractmethod
    def batch_embed_contents(
        self,
        model: str,
        texts: list[str],
        task_type: str = "RETRIEVAL_DOCUMENT",
    ) -> list[EmbeddingResult]:
        """Embed multiple texts in a single round-trip."""
